```{r setup, include=FALSE}
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
```

<style type="text/css">
body{ /* Normal  */
  font-size: 16px;
   min-width:1100px;        /* Suppose you want minimum width of 1000px */
   width: auto !important;  /* Firefox will set width as auto */
   width:1100px;            /* As IE6 ignores !important it will set width as 1100px; */
  }
h1 { /* Header 1 */
  font-size: 30px;
  color: DarkSlateGrey;
}
h2 { /* Header 2 */
    font-size: 26px;
  color: SlateGrey;
}
h3 { /* Header 3 */
  font-size: 22px;
  color: LightSlateGrey;
}
code.r{ /* Code block */
    font-size: 12px;
}
pre { /* Code block - determines code spacing between lines */
    font-size: 14px;
}
</style>


#
#
A full list of publications can be found [here](https://scholar.google.com/citations?user=mQzi2qsAAAAJ&hl=en).  
Publications indexed in Pubmed are [here](https://www.ncbi.nlm.nih.gov/pubmed/?term=maheu-giroux%5Bauthor%5D).  
Feel free to email me to obtain a copy of any of the papers below.  

#
# Peer-reviewed papers  
#  
## 2018  

> Tavitian-Exley I, Maheu-Giroux M, Platt L, Heimer R, Uusküla A, Levina O, Vickerman P, and Boily MC (2018). Differences in risk behaviors and HIV status between primary amphetamines and opioid injectors in Estonia and Russia. International Journal of Drug Policy. 53:96-105.


## 2017
> Tavitian-Exley I, Boily MC, Heimer R, Uusküla A, Levina O, and Maheu-Giroux M (2017). Polydrug use and HIV risk heterogeneity among people who inject drugs: a latent class analysis. AIDS and Behavior. DOI 10.1007/s10461-017-1836-0

> Maheu-Giroux M, Baral S, Vesga JF, Diouf D, Diabaté S, Alary M, Abo K, and Boily MC (2017). Anal intercourse among female sex workers in Côte d’Ivoire: prevalence, frequency, determinants, and model-based estimates of its population-level impact on HIV transmission. American Journal of Epidemiology. doi: 10.1093/aje/kwx244.

> Maheu-Giroux M, Vesga JF, Diabaté S, Alary M, Baral S, Diouf D, Abo K, and Boily MC (2017). Population-level impact of an accelerated HIV response plan to reach the UNAIDS 90-90-90 target in Côte d’Ivoire: insights from mathematical modeling. PLOS Medicine 14(6):e1002321.

> Kirakoya-Samadoulougou F, Jean K, and Maheu-Giroux M (2017). Uptake of HIV testing in Burkina Faso: an assessment of individual and community-level determinants. BMC Public Health 17(1):487.

> Maheu-Giroux M, Vesga JF, Diabaté S, Alary M, Baral S, Diouf D, Abo K, and Boily MC (2017). Changing dynamics of HIV transmission in Côte d’Ivoire: modeling which key populations acquired and transmitted HIV infections and estimating the impact of past HIV interventions (1976-2015). JAIDS Journal of Acquired Immune Deficiency Syndromes. (In Press)

> Maheu-Giroux M, Tanser F, Boily MC, Pillay D, Joseph SA, and Bäernighausen T (2017). Determinants of time from HIV infection to linkage-to-care in rural KwaZulu-Natal, South Africa. AIDS 31:1017-1024.

## 2016

> Castro MC, Maheu-Giroux M, Chiyaka C, and Singer BH (2016). Malaria incidence rates from time series of 2-wave panel surveys. PLOS Computational Biology. 12(8):e1005065.

> Maheu-Giroux M, Filippi V, Samadoulougou S, Castro MC, Maulet N, Meda N, Pouliot M, and Kirakoya-Samadoulougou F (2016). Risk factors for vaginal fistula symptoms in sub-Saharan Africa: a pooled analysis of national household surveys. BMC Pregnancy and Childbirth 16(1):1-10.


## 2015
> Joseph SA, Casapía M, Montresor A, Rahme E, Ward BJ, Marquis GS, Pezo L, Blouin B, Maheu-Giroux M, and Gyorkos TW (2015). The effect of deworming timing and frequency on growth in one-year old children living in an STH-endemic area of Peru: a randomized controlled trial. PLOS Neglected Tropical Diseases 9(10):e0004020.

> Maheu-Giroux M, Filippi V, Samadoulougou S, Castro MC, Maulet N, Meda N, and Kirakoya-Samadoulougou F (2015). Fistula in sub-Saharan Africa – Authors’ reply. The Lancet Global Health. 3(8):e442.

> Maheu-Giroux M, Filippi V, Samadoulougou S, Castro MC, Maulet N, Meda N, and Kirakoya-Samadoulougou F (2015). Prevalence of symptoms of vaginal fistula in 19 sub-Saharan Africa countries: a meta-analysis of national household survey data. The Lancet Global Health 3(5):e271-e278.

## 2014
> Joseph SA, Casapía M, Blouin B, Maheu-Giroux M, Rahme E, and Gyorkos TW (2014). Risk factors associated with malnutrition in one-year-old children living in the Peruvian Amazon. PLOS Neglected Tropical Diseases 8(12):e3369.

> Maheu-Giroux M and Castro MC (2014). Cost-effectiveness of larviciding for urban malaria control in Tanzania. Malaria Journal 13(1):447. (*Highly Accessed)

> Maheu-Giroux M and Castro MC (2014). Factors affecting providers’ delivery of Intermittent Preventive Therapy for malaria in pregnancy: a five-country analysis of national Service Provision Assessment surveys. Malaria Journal 13(1):440.

> Thériault FL, Maheu-Giroux M, Blouin B, Casapía M, and Gyorkos TW (2014). Effects of a post-deworming health hygiene education intervention on absenteeism in school-age children of the Peruvian Amazon. PLOS Neglected Tropical Diseases 8(8):e3007. 

> Samadoulougou S, Maheu-Giroux M, Kirakoya-Samadoulougou F, de Keukeleire M, Castro MC, and Robert A (2014). Multilevel and geo-statistical modeling of malaria risk in children of Burkina Faso. Parasites & Vectors 7(1):350.

> Tanser F, de Oliveira T, Maheu-Giroux M and Baernighausen TW (2014). Concentrated HIV epidemics within generalized ones in sub-Saharan Africa. Current Opinion in HIV and AIDS 9(2):115-125.

## 2013
> Gyorkos TW, Maheu-Giroux M, Blouin B, Saavedra L, and Casapía M (2013). Efficacy of a single dose of albendazole for soil-transmitted helminth infections in school children of Iquitos, Peru. Revista Peruana de Medicina Experimental y Salud Pública 30(4):601-607.

> Maheu-Giroux M and Castro MC (2013). Do malaria vector control measures impact disease-related behaviors and knowledge? Evidence from a large-scale larviciding intervention in Tanzania. Malaria Journal 12:422. (*Highly Accessed)

> Gyorkos TW, Maheu-Giroux M, Blouin B, and Casapía M (2013). Impact of health education on soil-transmitted helminth infections in schoolchildren of the Peruvian Amazon: A cluster-randomized controlled trial. PLOS Neglected Tropical Diseases 7(9):e2397.

> Maheu-Giroux M and Castro MC (2013). Impact of community-based larviciding on the prevalence of malaria infection in Dar es Salaam, Tanzania. PLOS ONE. 8(8):e71638. 

> Blouin B, Penny ME, Maheu-Giroux M, Casapía M, Aguilar E, Silva H, Creed-Kanashiro H, Joseph SA, Gagnon A, Rahme E, and Gyorkos TW (2013). Timing of umbilical cord clamping and infant anemia: the role of maternal anemia. Paediatrics & International Child Health. 33(2):79-85.

## 2012
> Gyorkos TW, Maheu-Giroux M, Blouin B, Creed-Kanashiro H, Casapía M, Aguilar E, Silva H, Joseph SA, and Penny ME (2012). A hospital policy change toward delayed cord clamping is effective in improving hemoglobin levels and anemia status of 8-month-old Peruvian infants. Journal of Tropical Pediatrics 58(6):435-440.

## 2011
> Blouin B, Penny ME, Casapía M, Aguilar E, Silva H, Joseph SA, Creed-Kanashiro H, Maheu-Giroux M, and Gyorkos TW (2011). Effect of a two-component intervention to change hospital practice from early to delayed umbilical cord clamping in the Peruvian Amazon. Pan American Journal of Public Health 29(5):322-328.

> Gyorkos TW, Maheu-Giroux M, Casapía M, Joseph SA, and Creed-Kanashiro H (2011). Stunting and helminth infection in early preschool-age children in a resource-poor community in the Amazon lowlands of Peru. Transactions of the Royal Society for Tropical Medicine & Hygiene 105(4):204-208.

> Maheu-Giroux M, Casapía M, and Gyorkos TW (2011). On the validity of self-reports and indirect reports to ascertain malaria prevalence in settings of hypoendemicity. Social Science & Medicine 72(5):635-640.

## 2010
> Maheu-Giroux M, Sotto-Calle VE, Casapía M, Berrang-Ford L, Buckeridge DL, Coomes OT, and Gyorkos TW (2010). Risk of malaria transmission from fish ponds in the Peruvian Amazon. Acta Tropica 115(1-2):112-118.

## 2007
> Maheu-Giroux M and de Blois S (2007). The landscape ecology of Phragmites australis invasion in networks of linear wetlands. Landscape Ecology 22(2):285-301.

## 2005
> Maheu-Giroux M and de Blois S (2005). Mapping the invasive species Phragmites australis in linear wetlands corridors. Aquatic Botany 83(4):310-320. (*Top 25 accessed articles)

#
#
# Editorials and book reviews 
> Maheu-Giroux M (2016). Oxantel pamoate and deworming programmes. The Lancet Infectious Diseases 16(1):5-6.

> Maheu-Giroux M (2014). How Medicine Became Modern – “The Remedy: Robert Koch, Arthur Conan Doyle, and the Quest to Cure Tuberculosis”. Science 346(6206):174.

> Maheu-Giroux M (2011). Change of mind: vaccines now to be used for cholera control in Haïti. Harvard College Global Health Review. (12/31/2011)

#
# Book section (short publication)
> Pauchard A and Maheu-Giroux M (2007). Case study 11.1 - Acacia dealbata invasion across multiple scales: conspicuous flowering species can help us study invasion patterns and processes (pages 166-167).  in H Strand, R Höft, J Strittholt, L Miles, N Horning, and E Fosnight, editors. Sourcebook on Remote Sensing and Biodiversity Indicators. Secretariat of the Convention on Biological Diversity, Montréal, Technical Series no. 32, 201 pages

#
# Reports
> Maheu-Giroux M (2017). A Bayesian framework for global, regional, and national estimates of violence against women statistics. Reported submitted to the World Health Organization, Dept. of Reproductive Health and Research. 88 pages.

> Maheu-Giroux M, Joseph L, Belisle P, Lancione S, and Eaton JW (2017). Assessing the Impact of Imperfect Immunoassays on HIV Prevalence Estimates from Surveys Conducted by The DHS Program. DHS Methodological Report No. 22. 58 pages. Rockville, MD, USA.

> Diabaté S, Maheu-Giroux M, Vesga JF, Boily MC, and Alary M (2015). Plan d’accélération de la réponse nationale au VIH en Côte d’Ivoire. Rapport présenté à ONUSIDA – Région d’Afrique de l’ouest et du centre. 145 pages.

> Maheu-Giroux M and Belvisi J (2007). Volet Biodiversité de l’Initiative Nationale d’Élaboration de Normes Agroenvironnementales - Démarche d’appui au développement de normes appliquées au projet pilote de l’écorégion des basses-terres du Saint-Laurent. Rapport présenté à Environnement Canada – INÉNA. 245 pages.

> Maheu-Giroux M, de Blois S, and Jobin B (2006). Suivi des habitats et des pressions anthropiques de quatre Réserves nationales de faune du Québec et leur périphérie à l’échelle du paysage. Environnement Canada, Service canadien de la faune, Région du Québec. 63 p. + annexes.

> Maheu-Giroux M, Boivin P, Brisson J, de Blois S, and Bouchard A (2003). Évaluation de la résistance de différents mélanges d'espèces végétales à l'envahissement d'espèces arborescentes > Protocole expérimental. Institut de Recherche en Biologie Végétale - Université de Montréal. 25 pages.
